name: DepthAI Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
      - '!v*-sdk'
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build and Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push (development)
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag luxonis/depthai:${{ github.sha }} \
            --output "type=image,push=true" .

      - name: Get Version
        if: startsWith(github.ref, 'refs/tags/v')
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push (release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag luxonis/depthai:${{ steps.vars.outputs.short_ref }} \
            --tag luxonis/depthai:latest \
            --output "type=image,push=true" .
