 name: OS Support

 on:
  workflow_dispatch:
  push:
    paths:
      - 'install_requirements.py'
      - '.github/workflows/test_install_requirements.yml'
      - 'requirements.txt'
      - 'requirements-optional.txt'
      - 'depthai_sdk/requirements.txt'

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   test_linux_fedora:
     runs-on: ubuntu-latest
     strategy:
       matrix:
          container_image: ["fedora:34", "fedora:35", "fedora:36"]
       fail-fast: false
     container:
       image: ${{ matrix.container_image }}
     steps:
       - uses: actions/checkout@v3
       - name: Install sudo
         if: startsWith(matrix.container_image, 'fedora') == true
         run: yum update -y && yum install -y sudo curl
       - name: Install dependencies
         run: |
           ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
           curl -fL https://docs.luxonis.com/install_dependencies.sh > install_dependencies.sh
           sed '/udevadm control --reload-rules && sudo udevadm trigger/d' install_dependencies.sh > tmp_script.sh
           bash tmp_script.sh
       - name: Install example requirements
         run: |
           python3 install_requirements.py
   test_linux_ubuntu:
     strategy:
       matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
          os: ["ubuntu-20.04", "ubuntu-22.04"]
       fail-fast: false
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
       - name: Install curl
         run: sudo apt-get update  -qq && sudo apt-get -qq install curl
       - uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
         run: |
           ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
           curl -fL https://docs.luxonis.com/install_dependencies.sh > install_dependencies.sh
           sed '/udevadm control --reload-rules && sudo udevadm trigger/d' install_dependencies.sh > tmp_script.sh
           bash tmp_script.sh
       - name: Install example requirements
         run: |
           python3 install_requirements.py
   test_macos:
      strategy:
        matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
          os: ["macos-11", "macos-12"]
        fail-fast: false
      runs-on: ${{ matrix.os }}
      steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
         run: |
           curl -fL https://docs.luxonis.com/install_dependencies.sh > install_dependencies.sh
           sed '/udevadm control --reload-rules && sudo udevadm trigger/d' install_dependencies.sh > tmp_script.sh
           bash tmp_script.sh
       - name: Install example requirements
         run: |
           python3 install_requirements.py
   test_windows:
      runs-on: windows-latest
      strategy:
        matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        fail-fast: false
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: ${{ matrix.python-version }}
      - name: Download chocolatey
        shell: pwsh
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Install dependencies
        shell: pwsh
        run: choco install cmake git python --version 3.10 pycharm-community -y
      - name: Install requrirements
        run: |
          python install_requirements.py

